apiVersion: v2
appVersion: v0.9.0
description: A Helm chart for KubeVirtBMC
home: https://kubevirtbmc.io
keywords:
- kubevirt
- cdi
- vm
- bmc
- ipmi
- redfish
maintainers:
- email: starbops@zespre.com
  name: starbops
  url: https://www.zespre.com
- email: anishbista053@gmail.com
  name: anishbista60
name: kubevirtbmc
sources:
- https://github.com/kubevirtbmc/chart
- https://github.com/kubevirtbmc/kubevirtbmc
type: application
version: 0.6.0
