apiVersion: v1
appVersion: 1.10.0
description: A Kubernetes operator that simplifies the management of Role Bindings
  and Service Accounts.
home: https://rbac-manager.docs.fairwinds.com
icon: https://raw.githubusercontent.com/FairwindsOps/charts/master/stable/rbac-manager/icon.png
keywords:
- rbac
- authorization
kubeVersion: '>= 1.22.0-0'
maintainers:
- email: andy@fairwinds.com
  name: sudermanjr
name: rbac-manager
sources:
- https://github.com/FairwindsOps/charts/tree/master/stable/rbac-manager
- https://github.com/FairwindsOps/rbac-manager
version: 2.0.0
