{{- if and .Values.msgTopologyOperator.enabled .Values.msgTopologyOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "rmqmto.labels" . | nindent 4 }}
  name: {{ template "rmqco.msgTopologyOperator.fullname.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "cloudpirates.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
rules:
  {{- if .Values.msgTopologyOperator.rbac.clusterRole.customRules }}
  {{- range .Values.msgTopologyOperator.rbac.clusterRole.customRules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ .resources | toYaml | nindent 6 }}
    verbs: {{ .verbs | toYaml | nindent 6 }}
  {{- end }}
  {{- else }}
  {{- if .Values.msgTopologyOperator.rbac.clusterRole.extraRules }}
  {{- range .Values.msgTopologyOperator.rbac.clusterRole.extraRules }}
  - apiGroups: {{ .apiGroups | toYaml | nindent 6 }}
    resources: {{ .resources | toYaml | nindent 6 }}
    verbs: {{ .verbs | toYaml | nindent 6 }}
  {{- end }}
  {{- end }}
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings
      - exchanges
      - federations
      - operatorpolicies
      - permissions
      - policies
      - queues
      - schemareplications
      - shovels
      - superstreams
      - topicpermissions
      - users
      - vhosts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings/finalizers
      - exchanges/finalizers
      - federations/finalizers
      - operatorpolicies/finalizers
      - permissions/finalizers
      - policies/finalizers
      - queues/finalizers
      - schemareplications/finalizers
      - shovels/finalizers
      - superstreams/finalizers
      - topicpermissions/finalizers
      - users/finalizers
      - vhosts/finalizers
    verbs:
      - update
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings/status
      - exchanges/status
      - federations/status
      - operatorpolicies/status
      - permissions/status
      - policies/status
      - queues/status
      - schemareplications/status
      - shovels/status
      - superstreams/status
      - topicpermissions/status
      - users/status
      - vhosts/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rabbitmq.com
    resources:
      - rabbitmqclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rabbitmq.com
    resources:
      - rabbitmqclusters/status
    verbs:
      - get
  {{- end }}
{{- end }}
