# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "nvcre.labels" . | nindent 4 }}
  name: nvcre-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvcre-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "nvcre.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
