# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "nvcre.labels" . | nindent 4 }}
    control-plane: manager
    release: prometheus
  name: {{ include "nvcre.resourceName" (dict "suffix" "metrics-monitor" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "nvcre.selectorLabels" . | nindent 6 }}
      control-plane: manager

{{- end }}
