# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "nvcre.labels" . | nindent 4 }}
    control-plane: manager
  name: {{ include "nvcre.resourceName" (dict "suffix" "metrics-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "nvcre.selectorLabels" . | nindent 4 }}
    control-plane: manager
