# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvcre.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvcre.labels" . | nindent 4 }}
