# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This rule is not used by the project nvcre itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to nvcre.nvidia.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "nvcre.labels" . | nindent 4 }}
  name: nvcre-workloadrun-viewer-role
rules:
- apiGroups:
  - nvcre.nvidia.com
  resources:
  - workloadruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvcre.nvidia.com
  resources:
  - workloadruns/status
  verbs:
  - get
