{{- if .Values.manageAuthSecret -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "stormforge-agent.authSecret" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "stormforge-agent.labels" . | nindent 4 }}
data:
  {{- if .Values.standbyMode }}
  STORMFORGE_CLIENT_ID: {{ "standbyMode" | b64enc | quote }}
  STORMFORGE_CLIENT_SECRET: {{ "standbyMode" | b64enc | quote }}
  STORMFORGE_ISSUER: {{ required "Chart value `stormforge.address` is required!" .Values.stormforge.address | b64enc | quote }}
  STORMFORGE_SERVER: {{ required "Chart value `stormforge.address` is required!" .Values.stormforge.address | b64enc | quote }}
  {{- else }}
  STORMFORGE_CLIENT_ID: {{ required "Chart value `authorization.clientID` is required!" .Values.authorization.clientID | b64enc | quote }}
  STORMFORGE_CLIENT_SECRET: {{ required "Chart value `authorization.clientSecret` is required!" .Values.authorization.clientSecret | b64enc | quote }}
  STORMFORGE_ISSUER: {{ required "Chart value `authorization.issuer` is required!" .Values.authorization.issuer | b64enc | quote }}
  STORMFORGE_SERVER: {{ required "Chart value `stormforge.address` is required!" .Values.stormforge.address | b64enc | quote }}
  {{- end -}}
{{- end -}}