{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stormforge-agent.fullname" . }}
  labels: {{- include "stormforge-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - workloadoptimizers/status
  verbs:
  - create
  - delete
  - patch
  - update
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

{{- if .Values.openshift }}{{ "\n" }}
# Rule for: OpenShift
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - anyuid
# Rule for: OpenShift operator-owned workloads
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - dnses
  - ingresscontrollers
  verbs:
  - get
  - list
  - watch
{{- end }}

{{- $rbacTypes :=
      concat (.Values.workloadResourceTypes | default list)
             (.Values.ownerResourceTypes | default list)
             (.Values.patchTargetTypes | default list) -}}
{{- with $rbacTypes }}{{ "\n" }}
{{- $gr := list -}}
  {{- range . -}}
  {{- $gr = append $gr (dict "group" .group "resource" .resource) -}}
{{- end -}}
# From Helm parameters: `workloadResourceTypes`, `ownerResourceTypes`, `patchTargetTypes`
{{- range ($gr | uniq) }}
- apiGroups:
  - {{ .group | quote }}
  resources:
  - {{ .resource | quote }}
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}

{{- with .Values.featureGates }}
{{- if .optimizeSparkOperator }}{{ "\n" }}
# Rule for feature: Optimize Spark Operator
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - scheduledsparkapplications
  - sparkapplications
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- if .optimizeGithubARC }}{{ "\n" }}
# Rule for feature: Optimize Github ARC
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  - autoscalingrunnersets
  - ephemeralrunners
  - ephemeralrunnersets
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}

{{- with .Values.rbac -}}
{{- if not .useViewRole }}{{ "\n" }}
# Minimum RBAC for Built-in Resources
- apiGroups:
    - optimize.stormforge.io
  resources:
    - optimizationconfigurations
    - clusteroptimizationconfigurations
    - workloadoptimizers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - namespaces
    - pods
    - replicationcontrollers
    - replicationcontrollers/scale
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - replicasets
    - replicasets/scale
    - statefulsets
    - statefulsets/scale
    - daemonsets
    - deployments
    - deployments/scale
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheuses
  verbs:
    - get
    - list
    - watch
{{- end}}
{{- if .additional }}{{ "\n" }}
# From Helm parameter: `rbac.additional`
{{ .additional }}
{{- end }}
{{- end }}

{{- end -}}
