annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - Release CRDs for operator [v0.73.1](https://github.com/VictoriaMetrics/operator/releases/tag/v0.73.1)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/operator/
    - name: Changelog
      url: https://docs.victoriametrics.com/helm/victoria-metrics-operator-crds/changelog/
    - name: App Changelog
      url: https://docs.victoriametrics.com/operator/changelog/
  artifacthub.io/operator: "true"
  artifacthub.io/readme: |
    # VictoriaMetrics Operator CRDs Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-metrics-operator-crds/).
    Changelog is [here](https://docs.victoriametrics.com/helm/victoria-metrics-operator-crds/changelog/).
apiVersion: v2
appVersion: v0.73.1
dependencies:
- name: crds
  repository: ""
  version: 0.0.*
description: VictoriaMetrics Operator CRDs
home: https://github.com/VictoriaMetrics/operator
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-operator-crds
sources:
- https://github.com/VictoriaMetrics/helm-charts
- https://github.com/VictoriaMetrics/operator
type: application
version: 0.13.1
