---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stormforge-agent.agentName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.workload.serviceAnnotations }}
  annotations: {{ toYaml .Values.workload.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: {{ include "stormforge-agent.agentComponent" . }}
    {{- include "stormforge-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "stormforge-agent.agentSelectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: management 
    protocol: TCP
    port: 6060
    targetPort: 6060
