apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: mpi-operator
    app.kubernetes.io/component: mpijob
    app.kubernetes.io/name: mpi-operator
  name: mpi-operator
  namespace: mpi-operator