# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.mongodb.tls.enabled }}
{{- if .Values.usePerconaOperator }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-app-client-cert
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ include "nvsentinel.certificates.secretName" . }}
  duration: 8760h
  renewBefore: 360h
  commonName: mongo-user-client
  subject:
    organizations:
      - Nvidia
    organizationalUnits:
      - DGXC
    localities:
      - SantaClara
    provinces:
      - California
    countries:
      - US
  issuerRef:
    name: mongodb-psmdb-issuer
    kind: Issuer
    group: cert-manager.io
{{- else }}

{{- $replicaCount := int .Values.mongodb.replicaCount }}
{{- range $i := until $replicaCount }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-server-cert-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: mongo-server-cert-{{ $i }}
  duration: 8760h   # 1 year
  renewBefore: 360h # 15 days before expiration
  commonName: {{ printf "%s-mongo-%d" $.Release.Namespace $i }}
  dnsNames:
    - {{ printf "mongodb-%d.mongodb-headless.%s.svc.cluster.local" $i $.Release.Namespace }}
    - {{ printf "mongodb-headless.%s.svc.cluster.local" $.Release.Namespace }}
  issuerRef:
    name: mongo-ca-issuer
    kind: Issuer
---
{{- end }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-app-client-cert
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ include "nvsentinel.certificates.secretName" . }}
  duration: 8760h
  renewBefore: 360h
  commonName: mongo-user-client
  subject:
    organizations:
      - Nvidia
    organizationalUnits:
      - DGXC
    localities:
      - SantaClara
    provinces:
      - California
    countries:
      - US
  issuerRef:
    name: mongo-ca-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mongo-ca-issuer
  namespace: {{ $.Release.Namespace }}
spec:
  ca:
    secretName: mongo-root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca-issuer
  namespace: {{ $.Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-root-ca
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: mongo-root-ca
  secretName: mongo-root-ca-secret
  duration: 87600h   # 10 years
  renewBefore: 720h  # 30 days before expiration
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-ca-issuer
    kind: Issuer
{{- end }}
{{- end }}
