name: BulwarkGitLeaks
on: [pull_request]

concurrency:
  group: gitleaks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/spectro-dev-public/bulwark/gitleaks@sha256:1ae9377df2b48b310eee67260a25a68f0d60b3cb6d662ce28cd45ef1b1426a1a # latest
      env:
        REPO: ${{ github.event.repository.name }}
        BRANCH: ${{ github.head_ref || github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_CONFIG: config.toml
    steps:

      - name: run-bulwark-gitleaks-scan
        if: github.event.pull_request.head.repo.full_name == github.repository
        shell: sh
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: /workspace/bulwark -name CodeSASTGitLeaks -target $REPO -tags "branch:$BRANCH,options:--log-opts origin..HEAD"

      - name: run-bulwark-gitleaks-scan-from-fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        shell: sh
        env:
          FORK_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          BASE_REPO: ${{ github.repository }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          git clone "https://github.com/${FORK_REPO}.git" -b "${BRANCH}" "${REPO}"
          cd "${REPO}"
          git remote add scRepo "https://github.com/${BASE_REPO}.git"
          git fetch scRepo
          /workspace/bulwark -name CodeSASTGitLeaks -target pwd -tags "branch:${BRANCH},options:--log-opts HEAD..scRepo/${BASE_REF}"

      - name: check-result
        shell: sh
        run: |
          resultPath=./$REPO/gitleaks.json
          cat $resultPath | grep -v \"Match\"\: | grep -v \"Secret\"\:
          total_failed_tests=`cat $resultPath | grep \"Fingerprint\"\: | wc -l`
          if [ "$total_failed_tests" -gt 0 ]; then
            echo "GitLeaks validation check failed with above findings..."
            exit 1
          else 
            echo "GitLeaks validation check passed"
          fi
